on: push
name: Build and Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
